export const trailers = [
  { time: '0', title: 'Mission Impossible 7 Dead Reckoning' },
  { time: '126', title: 'John Wick 4' },
  { time: '192', title: 'Avatar 2 The Way of Water' },
  { time: '288', title: 'Spider Man Across the Spider Verse' },
  { time: '432', title: 'Troll' },
  { time: '473', title: 'Puss in Boots 2 The Last Wish' },
  { time: '649', title: 'Black Panther 2 Wakanda Forever' },
  { time: '776', title: 'Black Adam' },
  { time: '850', title: 'Shazam 2 Fury of the Gods' },
  { time: '995', title: 'Dungeons And Dragons Honor Among Thieves' },
  { time: '1122', title: 'Samaritan' },
  { time: '1280', title: 'Teen Wolf' },
  { time: '1352', title: 'After Ever Happy' },
  { time: '1472', title: 'Strange World' },
  { time: '1556', title: 'Smile' },
  { time: '1635', title: 'Halloween Ends' },
  { time: '1770', title: 'Prey for the Devil' },
  { time: '1914', title: 'Triangle of Sadness' },
  { time: '2072', title: 'Emily' },
  { time: '2193', title: 'The Menu' },
  { time: '2322', title: 'Me Time' },
  { time: '2474', title: 'The Hunger Games: The Ballad of Songbirds and Snakes' },
  { time: '2557', title: 'Mortal Kombat Legends Snow Blind' },
  { time: '2685', title: "Don't Worry Darling" },
  { time: '2829', title: 'The Woman King' },
  { time: '3005', title: 'The Banshees of Inisherin' }
]